name: GitHub-Contributions-JSON

on:
    schedule:
        - cron: "0 */12 * * *"
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        name: update-contributions-json
        steps:
            - uses: actions/checkout@v4
            - run: |
                  node src/contributions.js

            - uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - name: Commit & Push
              run: |
                  git config user.name Pi
                  git config user.email 90981829+ItsPi3141@users.noreply.github.com
                  git add -A .
                  git commit -m "Updated contributions data"
                  git push
