name: GitHub-Profile-3D-Contrib

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: generate-github-profile-3d-contrib
        steps:
            - uses: actions/checkout@v4
            - uses: yoshi389111/github-profile-3d-contrib@0.7.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  USERNAME: ${{ github.repository_owner }}
                  SETTING_JSON: profile-3d-contrib/settings.json

            - uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - name: Commit & Push
              run: |
                  git config user.name Pi
                  git config user.email 90981829+ItsPi3141@users.noreply.github.com
                  git add -A .
                  git commit -m "Generated 3D contributions graph"
                  git push
